# Generated by Django 3.1.6 on 2021-03-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210217_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
