# Generated by Django 3.1.6 on 2021-02-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
    ]
