# Generated by Django 3.1.6 on 2021-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_register_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_activity', models.CharField(blank=True, max_length=30, verbose_name='Name activity')),
                ('rout_length', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Rout length')),
                ('duration', models.TimeField(verbose_name='Duration')),
                ('date', models.DateTimeField(verbose_name='Date/Time')),
            ],
        ),
    ]
