# Generated by Django 3.1.6 on 2021-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(verbose_name='date/Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, max_length=30, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_activity',
            field=models.CharField(blank=True, max_length=30, verbose_name='name_activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rout_length',
            field=models.CharField(blank=True, max_length=30, verbose_name='rout_length'),
        ),
    ]
