# Generated by Django 3.1.6 on 2021-02-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_activity_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='author',
            new_name='user',
        ),
    ]
