# Generated by Django 3.1.6 on 2021-02-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20210221_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='username',
        ),
    ]
