# Generated by Django 3.1.6 on 2021-02-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20210221_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='username',
            new_name='user',
        ),
    ]
