# Generated by Django 3.1.6 on 2021-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20210227_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='calories',
            field=models.CharField(blank=True, max_length=5, verbose_name='calories'),
        ),
    ]
