# Generated by Django 3.1.6 on 2021-02-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_activity_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='weight',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
