# Generated by Django 3.1.6 on 2021-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_activity_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='all_duration',
            field=models.CharField(blank=True, max_length=30, verbose_name='duration'),
        ),
    ]
