# Generated by Django 3.1.6 on 2021-02-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_activity_all_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='all_duration',
        ),
    ]
