# Generated by Django 3.1.6 on 2021-02-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_remove_activity_all_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_duration',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
