# Generated by Django 3.1.6 on 2021-03-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_auto_20210303_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='all_duration',
        ),
        migrations.AddField(
            model_name='activity',
            name='all_duration',
            field=models.CharField(blank=True, max_length=30, verbose_name='all duration'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='media/img'),
        ),
    ]
