# Generated by Django 3.1.6 on 2021-03-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_auto_20210306_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_duration_profile',
            field=models.CharField(blank=True, max_length=30, verbose_name='all duration_'),
        ),
    ]
