# Generated by Django 3.1.6 on 2021-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_auto_20210306_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_length',
            field=models.CharField(blank=True, max_length=30, verbose_name='all length'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='all_length',
            field=models.CharField(blank=True, max_length=30, verbose_name='all length'),
        ),
    ]
