# Generated by Django 3.1.6 on 2021-03-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0023_auto_20210307_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='all_length',
        ),
    ]
