# Generated by Django 3.1.6 on 2021-03-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_remove_profile_all_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date/Time'),
        ),
    ]
