# Generated by Django 3.1.6 on 2021-03-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_auto_20210308_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageProfile',
            new_name='Image',
        ),
    ]
