# Generated by Django 3.1.6 on 2021-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0028_activity_all_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='av_speed',
            field=models.CharField(blank=True, max_length=30, verbose_name='all duration'),
        ),
    ]
